version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    labels:
      # Setting labels replaces Dependabot's defaults, so keep them
      - "dependencies"
      - "github_actions"
      # Skips the change log check in .github/workflows/changelog.yml
      - "skip changelog"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      # Check for updates to Python dependencies every week
      interval: "weekly"
    labels:
      # Setting labels replaces Dependabot's defaults, so keep them
      - "dependencies"
      - "python"
      # Skips the change log check in .github/workflows/changelog.yml
      - "skip changelog"
    groups:
      python-dependencies:
        patterns:
          - "*"
